#!/bin/sh

TMP="${XDG_RUNTIME_DIR:-/tmp}/youtube_download"

check() {
  if ! command -v yt-dlp > /dev/null; then
    die "yt-dlp not installed"
  fi

  if ! command -v ffmpeg > /dev/null; then
    die "ffmpeg not installed"
  fi

  if [ $# -eq 0 ]; then
    die "URL required"
  fi

  if [ -e "$TMP" ]; then
    die "directory '$TMP': already exists"
  fi
}

video() {
  while [ $# -gt 0 ]; do
    printf "file %s.mkv\n" $# >> "$TMP/0"

    yt-dlp --ignore-config --no-cache-dir --no-playlist \
      --quiet --progress --paths "$TMP" --output $# --merge-output-format mkv \
      --format bestvideo+bestaudio --format-sort vcodec:h264,acodec:opus \
      --sponsorblock-remove all "$1" || return

    shift
  done

  OUTPUT=$(date -u +%Y%m%d_%H%M%S).mp4

  ffmpeg -f concat -i "$TMP/0" -c copy "$TMP/$OUTPUT" -loglevel error || return

  mv -f "$TMP/$OUTPUT" ./
}

audio() {
  while [ $# -gt 0 ]; do
    printf "file %s.webm\n" $# >> "$TMP/0"

    yt-dlp --ignore-config --no-cache-dir --no-playlist \
      --quiet --progress --paths "$TMP" --output "${#}.%(ext)s" \
      --format 'bestaudio[ext=webm]' --format-sort acodec:opus \
      --sponsorblock-remove all "$1" || return

    shift
  done

  OUTPUT=$(date -u +%Y%m%d_%H%M%S).mp3

  ffmpeg -f concat -i "$TMP/0" "$TMP/$OUTPUT" -loglevel error || return

  mv -f "$TMP/$OUTPUT" ./
}

pre() {
  trap 'rm -rf "$TMP"; exit 1' HUP INT TERM

  install -d -m 700 "$TMP"
}

post() {
  ret=$?

  rm -rf "$TMP"

  exit $ret
}

die() {
  printf "youtube: %s\n" "$*" >&2
  exit 1
}

RST='\033[0;00m'
GRN='\033[0;32m'
YLW='\033[0;33m'

usage() {
  printf "%b\n" "${YLW}USAGE${RST}:"
  printf "%s\n" "    youtube [SUBCOMMAND] [URL] ..."
  printf "\n"
  printf "%b\n" "${YLW}SUBCOMMANDS${RST}:"
  printf "%b\n" "    ${GRN}v${RST}, ${GRN}video${RST}    Download .mp4 using h264 and opus"
  printf "%b\n" "    ${GRN}a${RST}, ${GRN}audio${RST}    Download .mp3 using opus"
}

case $1 in
  v | video)
    shift
    check "$@"
    pre
    video "$@"
    post
    ;;

  a | audio)
    shift
    check "$@"
    pre
    audio "$@"
    post
    ;;

  *)
    usage >&2
    ;;
esac
